import React, { useState } from 'react';
import { Cpu, Plus, Trash2, ArrowRight, Play, Sparkles, Copy, Check, Database, Filter, Layers, Download } from 'lucide-react';
import { PipelineStep } from '../../types/spark';

interface VisualPipelineBuilderProps {
  onRunInNotebook: (code: string) => void;
}

const INITIAL_STEPS: PipelineStep[] = [
  {
    id: 'step-1',
    type: 'Source',
    title: 'Load E-Commerce Sales',
    config: { dataset: 'ecommerce_sales', format: 'parquet' }
  },
  {
    id: 'step-2',
    type: 'Filter',
    title: 'Filter Active Region & Discounted',
    config: { column: 'is_discounted', operator: '==', value: 'true' }
  },
  {
    id: 'step-3',
    type: 'GroupBy',
    title: 'Aggregate Revenue by Region',
    config: { groupColumn: 'region', aggFunc: 'sum', aggColumn: 'price' }
  },
  {
    id: 'step-4',
    type: 'Sink',
    title: 'Write Output Delta Lake',
    config: { format: 'delta', path: 's3a://analytics-bucket/region_sales_delta' }
  }
];

export const VisualPipelineBuilder: React.FC<VisualPipelineBuilderProps> = ({ onRunInNotebook }) => {
  const [steps, setSteps] = useState<PipelineStep[]>(INITIAL_STEPS);
  const [copied, setCopied] = useState<boolean>(false);

  // Generate PySpark Code dynamically from steps
  const generateCodeFromSteps = (): string => {
    let py = `# PySpark ETL Pipeline Generated by Spark Studio Visual Builder\n`;
    py += `from pyspark.sql import SparkSession\n`;
    py += `from pyspark.sql import functions as F\n\n`;
    py += `spark = SparkSession.builder.appName("VisualPipelineETL").getOrCreate()\n\n`;

    let currentVar = 'df';

    steps.forEach((step, idx) => {
      if (step.type === 'Source') {
        py += `# Step ${idx + 1}: ${step.title}\n`;
        py += `${currentVar} = spark.read.table("${step.config.dataset || 'ecommerce_sales'}")\n\n`;
      } else if (step.type === 'Filter') {
        const nextVar = `df_filtered_${idx}`;
        py += `# Step ${idx + 1}: ${step.title}\n`;
        py += `${nextVar} = ${currentVar}.filter(F.col("${step.config.column || 'region'}").isNotNull() & (F.col("${step.config.column || 'is_discounted'}") == ${step.config.value || 'True'}))\n\n`;
        currentVar = nextVar;
      } else if (step.type === 'GroupBy') {
        const nextVar = `df_agg_${idx}`;
        py += `# Step ${idx + 1}: ${step.title}\n`;
        py += `${nextVar} = ${currentVar}.groupBy("${step.config.groupColumn || 'region'}") \\\n`;
        py += `    .agg(F.round(F.sum("${step.config.aggColumn || 'price'}"), 2).alias("total_revenue")) \\\n`;
        py += `    .orderBy(F.col("total_revenue").desc())\n\n`;
        currentVar = nextVar;
      } else if (step.type === 'Sink') {
        py += `# Step ${idx + 1}: ${step.title}\n`;
        py += `${currentVar}.write.format("${step.config.format || 'delta'}").mode("overwrite").save("${step.config.path || 's3a://data/output'}")\n`;
      }
    });

    py += `\n${currentVar}.show(10)`;
    return py;
  };

  const generatedPySparkCode = generateCodeFromSteps();

  const handleAddStep = (type: PipelineStep['type']) => {
    const newId = 'step-' + (steps.length + 1);
    const newStep: PipelineStep = {
      id: newId,
      type,
      title: `${type} Step ${steps.length + 1}`,
      config: type === 'Filter' ? { column: 'region', value: 'North America' } : { groupColumn: 'category', aggFunc: 'sum', aggColumn: 'price' }
    };
    setSteps([...steps, newStep]);
  };

  const handleRemoveStep = (id: string) => {
    setSteps(steps.filter(s => s.id !== id));
  };

  const handleCopyCode = () => {
    navigator.clipboard.writeText(generatedPySparkCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-6">
      {/* Top Banner */}
      <div className="bg-slate-900 rounded-2xl border border-slate-800 p-5 shadow-sm flex flex-wrap items-center justify-between gap-4">
        <div>
          <div className="flex items-center space-x-2">
            <Cpu className="w-5 h-5 text-amber-500" />
            <h2 className="font-bold text-slate-100 text-lg">Visual PySpark Pipeline Constructor</h2>
          </div>
          <p className="text-xs text-slate-400 mt-1">
            Build production-grade PySpark ETL pipelines step-by-step with real-time PySpark compilation.
          </p>
        </div>

        <div className="flex items-center space-x-2">
          <button
            onClick={handleCopyCode}
            className="flex items-center space-x-1.5 bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 px-3 py-2 rounded-xl text-xs font-semibold transition-all"
          >
            {copied ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
            <span>{copied ? 'Copied' : 'Copy Code'}</span>
          </button>

          <button
            onClick={() => onRunInNotebook(generatedPySparkCode)}
            className="flex items-center space-x-2 bg-gradient-to-r from-amber-500 to-orange-500 hover:from-amber-600 hover:to-orange-600 text-white px-4 py-2 rounded-xl text-xs font-semibold shadow-md shadow-orange-500/20 transition-all"
          >
            <Play className="w-4 h-4 fill-current" />
            <span>Load & Run in Notebook</span>
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Left Col: Step Nodes Builder */}
        <div className="bg-slate-900 rounded-2xl border border-slate-800 p-6 shadow-md space-y-4">
          <div className="flex items-center justify-between pb-3 border-b border-slate-800">
            <span className="font-bold text-xs text-slate-200 uppercase tracking-wider">Pipeline Steps ({steps.length})</span>
            <div className="flex items-center space-x-1">
              <button
                onClick={() => handleAddStep('Filter')}
                className="bg-slate-800 hover:bg-slate-700 text-slate-300 text-[11px] px-2.5 py-1 rounded-lg border border-slate-700 flex items-center space-x-1"
              >
                <Plus className="w-3 h-3" />
                <span>+ Filter</span>
              </button>
              <button
                onClick={() => handleAddStep('GroupBy')}
                className="bg-slate-800 hover:bg-slate-700 text-slate-300 text-[11px] px-2.5 py-1 rounded-lg border border-slate-700 flex items-center space-x-1"
              >
                <Plus className="w-3 h-3" />
                <span>+ GroupBy</span>
              </button>
            </div>
          </div>

          <div className="space-y-3">
            {steps.map((step, idx) => (
              <div key={step.id} className="bg-slate-950 p-4 rounded-xl border border-slate-800 space-y-3">
                <div className="flex items-center justify-between">
                  <div className="flex items-center space-x-2.5">
                    <span className="w-5 h-5 rounded-full bg-amber-500/10 text-amber-400 border border-amber-500/20 text-[10px] font-bold flex items-center justify-center font-mono">
                      {idx + 1}
                    </span>
                    <span className="font-semibold text-xs text-white">{step.title}</span>
                    <span className="px-2 py-0.5 bg-slate-800 text-slate-400 rounded text-[10px] font-mono">{step.type}</span>
                  </div>

                  {step.type !== 'Source' && step.type !== 'Sink' && (
                    <button
                      onClick={() => handleRemoveStep(step.id)}
                      className="text-slate-500 hover:text-red-400 p-1 rounded transition-colors"
                    >
                      <Trash2 className="w-3.5 h-3.5" />
                    </button>
                  )}
                </div>

                {/* Config Controls */}
                {step.type === 'Source' && (
                  <div className="grid grid-cols-2 gap-2 text-xs font-mono">
                    <div>
                      <span className="text-[10px] text-slate-500 block">Dataset:</span>
                      <select
                        value={step.config.dataset}
                        onChange={e => {
                          const updated = [...steps];
                          updated[idx].config.dataset = e.target.value;
                          setSteps(updated);
                        }}
                        className="bg-slate-900 border border-slate-800 rounded p-1.5 text-slate-200 w-full"
                      >
                        <option value="ecommerce_sales">ecommerce_sales</option>
                        <option value="server_access_logs">server_access_logs</option>
                        <option value="iot_sensors">iot_sensors</option>
                      </select>
                    </div>
                  </div>
                )}

                {step.type === 'Filter' && (
                  <div className="grid grid-cols-2 gap-2 text-xs font-mono">
                    <div>
                      <span className="text-[10px] text-slate-500 block">Filter Column:</span>
                      <input
                        type="text"
                        value={step.config.column || 'region'}
                        onChange={e => {
                          const updated = [...steps];
                          updated[idx].config.column = e.target.value;
                          setSteps(updated);
                        }}
                        className="bg-slate-900 border border-slate-800 rounded p-1.5 text-slate-200 w-full"
                      />
                    </div>
                    <div>
                      <span className="text-[10px] text-slate-500 block">Filter Value:</span>
                      <input
                        type="text"
                        value={step.config.value || 'True'}
                        onChange={e => {
                          const updated = [...steps];
                          updated[idx].config.value = e.target.value;
                          setSteps(updated);
                        }}
                        className="bg-slate-900 border border-slate-800 rounded p-1.5 text-slate-200 w-full"
                      />
                    </div>
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>

        {/* Right Col: Compiled PySpark Code Preview */}
        <div className="bg-slate-900 rounded-2xl border border-slate-800 p-6 shadow-md flex flex-col justify-between space-y-4">
          <div>
            <div className="flex items-center justify-between pb-3 border-b border-slate-800 mb-4">
              <span className="font-bold text-xs text-amber-400 uppercase tracking-wider font-mono">Auto-Compiled PySpark Code</span>
              <span className="text-[10px] text-slate-500 font-mono">Live Sync Enabled</span>
            </div>

            <pre className="bg-slate-950 p-4 rounded-xl border border-slate-800 font-mono text-xs text-emerald-400 overflow-x-auto whitespace-pre leading-relaxed">
              {generatedPySparkCode}
            </pre>
          </div>
        </div>
      </div>
    </div>
  );
};
