import React, { useState, useRef } from 'react';
import { Bot, Sparkles, CheckCircle2, Play, RefreshCw, X, ArrowRight, GitPullRequest, ShieldCheck, Code, Cpu, Terminal, ExternalLink, Copy, Check, Volume2 } from 'lucide-react';
import { SparkExecutionEngine } from '../../engine/sparkEngine';
import { generateSpeechForText } from '../../engine/aiService';

interface JulesAgentModalProps {
  isOpen: boolean;
  onClose: () => void;
  currentCode: string;
  currentMode: 'pyspark' | 'sql';
  onApplyPatch: (code: string) => void;
}

interface AgentStep {
  id: number;
  title: string;
  detail: string;
  status: 'pending' | 'running' | 'completed';
}

export const JulesAgentModal: React.FC<JulesAgentModalProps> = ({
  isOpen,
  onClose,
  currentCode,
  currentMode,
  onApplyPatch,
}) => {
  const [taskPrompt, setTaskPrompt] = useState<string>(
    'Optimize PySpark code for high throughput: convert wide shuffles to BroadcastHashJoin, add AQE hints, and write pytest unit tests.'
  );
  const [isAgentRunning, setIsAgentRunning] = useState<boolean>(false);
  const [activeStep, setActiveStep] = useState<number>(0);
  const [patchResult, setPatchResult] = useState<string | null>(null);
  const [summaryNotes, setSummaryNotes] = useState<string | null>(null);
  const [copied, setCopied] = useState<boolean>(false);
  const [isSpeaking, setIsSpeaking] = useState<boolean>(false);
  const audioRef = useRef<HTMLAudioElement | null>(null);

  const predefinedTasks = [
    {
      title: 'Pandas to PySpark Migration',
      prompt: 'Refactor this Pandas ETL logic into distributed PySpark DataFrame transformations using F.col and broadcast lookup tables.',
    },
    {
      title: 'Spark Shuffle & OOM Risk Audit',
      prompt: 'Analyze memory allocation, detect potential skewed keys in groupBy/join operations, and add explicit partition key repartitioning.',
    },
    {
      title: 'Unit Test Suite Generation',
      prompt: 'Generate PySpark unit tests using pytest and spark.createDataFrame with mock schema fixtures for this pipeline.',
    },
    {
      title: 'AQE & Catalyst Optimization',
      prompt: 'Add Adaptive Query Execution (AQE) configurations and coalesce hints to eliminate small file outputs.',
    },
  ];

  const stepsList: AgentStep[] = [
    { id: 1, title: 'Parsing & AST Analysis', detail: 'Analyzing PySpark DAG expression trees and schema signatures...', status: activeStep > 1 ? 'completed' : activeStep === 1 ? 'running' : 'pending' },
    { id: 2, title: 'Catalyst Physical Plan Inspection', detail: 'Checking for ShuffleExchange bottlenecks, spill-to-disk risks, and key skew...', status: activeStep > 2 ? 'completed' : activeStep === 2 ? 'running' : 'pending' },
    { id: 3, title: 'Autonomous Code Refactoring', detail: 'Applying BroadcastJoin optimizations, predicate pushdowns, and AQE hints...', status: activeStep > 3 ? 'completed' : activeStep === 3 ? 'running' : 'pending' },
    { id: 4, title: 'Synthetic Spark Execution Validation', detail: 'Executing patch in local Spark engine to verify output consistency...', status: activeStep > 4 ? 'completed' : activeStep === 4 ? 'running' : 'pending' },
  ];

  const handleRunJulesAgent = async () => {
    setIsAgentRunning(true);
    setActiveStep(1);
    setPatchResult(null);

    // Simulate Jules Agent step-by-step agentic execution
    await new Promise((r) => setTimeout(r, 800));
    setActiveStep(2);
    await new Promise((r) => setTimeout(r, 900));
    setActiveStep(3);
    await new Promise((r) => setTimeout(r, 1000));
    setActiveStep(4);
    await new Promise((r) => setTimeout(r, 700));

    // Generated Jules patch code
    const generatedPatch = `# Jules Agent Refactored & Optimized PySpark Pipeline
# Task: ${taskPrompt}
# Generated by Jules Autonomous Spark Agent

from pyspark.sql import SparkSession
import pyspark.sql.functions as F

# 1. Enable Adaptive Query Execution (AQE)
spark.conf.set("spark.sql.adaptive.enabled", "true")
spark.conf.set("spark.sql.adaptive.coalescePartitions.enabled", "true")

# 2. Read input dataframe with pushdown filter
df = spark.read.table("ecommerce_sales") \\
    .filter(F.col("region").isNotNull() & (F.col("price") > 0))

# 3. Broadcast small lookup table to eliminate ShuffleExchange
lookup_regions = spark.createDataFrame([
    ("North America", "NA_ZONE_1"),
    ("Europe", "EU_ZONE_2"),
    ("Asia-Pacific", "APAC_ZONE_3"),
], ["region", "zone_code"])

# 4. Perform Broadcast Hash Join & Aggregation
optimized_sales = df.join(F.broadcast(lookup_regions), "region", "left") \\
    .groupBy("region", "zone_code") \\
    .agg(
        F.count("order_id").alias("total_orders"),
        F.round(F.sum("price"), 2).alias("total_revenue"),
        F.round(F.avg("price"), 2).alias("avg_order_value")
    ) \\
    .coalesce(4) \\
    .orderBy(F.col("total_revenue").desc())

optimized_sales.show(10)

# --- Jules Generated PySpark Unit Test ---
# def test_sales_aggregation(spark_fixture):
#     test_data = [("North America", 100.0, "O1"), ("North America", 50.0, "O2")]
#     df_test = spark_fixture.createDataFrame(test_data, ["region", "price", "order_id"])
#     res = df_test.groupBy("region").agg(F.sum("price").alias("total_revenue"))
#     assert res.collect()[0]["total_revenue"] == 150.0
`;

    setPatchResult(generatedPatch);
    const finalNotes = 'Jules optimized 1 ShuffleExchange operation to BroadcastHashJoin, enabled AQE coalescing, and appended a pytest validation suite.';
    setSummaryNotes(finalNotes);
    setActiveStep(5);
    setIsAgentRunning(false);

    // Auto-generate speech for the summary notes in the background
    generateSpeechForText(finalNotes).then((base64) => {
      if (base64) {
        const audioSrc = `data:audio/wav;base64,${base64}`;
        audioRef.current = new Audio(audioSrc);
        audioRef.current.onended = () => setIsSpeaking(false);
      }
    });
  };

  const handleCopyPatch = () => {
    if (!patchResult) return;
    navigator.clipboard.writeText(patchResult);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePlaySpeech = () => {
    if (audioRef.current) {
      if (isSpeaking) {
        audioRef.current.pause();
        audioRef.current.currentTime = 0;
        setIsSpeaking(false);
      } else {
        audioRef.current.play();
        setIsSpeaking(true);
      }
    }
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/80 backdrop-blur-md p-4 animate-in fade-in duration-200">
      <div className="bg-slate-900 border border-slate-800 rounded-2xl w-full max-w-4xl shadow-2xl flex flex-col max-h-[88vh] overflow-hidden">
        {/* Header */}
        <div className="px-6 py-4 border-b border-slate-800 bg-slate-950 flex items-center justify-between">
          <div className="flex items-center space-x-3">
            <div className="p-2.5 bg-gradient-to-tr from-cyan-500 to-blue-600 rounded-xl text-white shadow-lg shadow-cyan-500/20">
              <Bot className="w-5 h-5" />
            </div>
            <div>
              <div className="flex items-center space-x-2">
                <h3 className="text-base font-bold text-slate-100">Jules AI Agent</h3>
                <span className="px-2 py-0.5 text-[10px] font-mono font-semibold bg-cyan-500/10 text-cyan-400 border border-cyan-500/20 rounded-full">
                  Autonomous Spark Engineer
                </span>
              </div>
              <p className="text-xs text-slate-400">
                Autonomous agentic code refactoring, test generation & Spark CI/CD pipeline automation
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-slate-400 hover:text-slate-200 hover:bg-slate-800 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Body */}
        <div className="flex-1 overflow-y-auto p-6 space-y-6">
          {/* Preset Prompts */}
          <div>
            <label className="text-xs font-semibold text-slate-300 block mb-2">Preset Autonomous Tasks:</label>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
              {predefinedTasks.map((task, idx) => (
                <button
                  key={idx}
                  onClick={() => setTaskPrompt(task.prompt)}
                  className="p-2.5 bg-slate-950 hover:bg-slate-800/80 border border-slate-800 rounded-xl text-left text-xs text-slate-300 transition-all flex flex-col space-y-1 hover:border-cyan-500/40"
                >
                  <span className="font-semibold text-cyan-400 flex items-center gap-1.5">
                    <Sparkles className="w-3.5 h-3.5" />
                    {task.title}
                  </span>
                  <span className="text-[11px] text-slate-400 line-clamp-1">{task.prompt}</span>
                </button>
              ))}
            </div>
          </div>

          {/* Task Prompt Area */}
          <div className="space-y-2">
            <label className="text-xs font-semibold text-slate-300">Task Instruction for Jules:</label>
            <textarea
              value={taskPrompt}
              onChange={(e) => setTaskPrompt(e.target.value)}
              rows={3}
              className="w-full bg-slate-950 border border-slate-800 rounded-xl p-3 text-xs text-slate-200 font-mono focus:outline-none focus:border-cyan-500"
            />
          </div>

          {/* Start Agent Execution Button */}
          <div className="flex items-center justify-between">
            <div className="text-xs text-slate-400 flex items-center gap-2">
              <Cpu className="w-4 h-4 text-cyan-400" />
              <span>Target: Active PySpark Code Session ({currentMode.toUpperCase()})</span>
            </div>

            <button
              onClick={handleRunJulesAgent}
              disabled={isAgentRunning}
              className="px-5 py-2.5 bg-gradient-to-r from-cyan-500 to-blue-600 hover:from-cyan-400 hover:to-blue-500 text-white font-bold text-xs rounded-xl shadow-lg shadow-cyan-500/20 transition-all flex items-center gap-2 disabled:opacity-50"
            >
              {isAgentRunning ? (
                <>
                  <RefreshCw className="w-4 h-4 animate-spin" />
                  <span>Jules Working...</span>
                </>
              ) : (
                <>
                  <Play className="w-4 h-4 fill-current" />
                  <span>Launch Jules Agent Task</span>
                </>
              )}
            </button>
          </div>

          {/* Agent Progress Tracker */}
          {(isAgentRunning || activeStep > 0) && (
            <div className="bg-slate-950 border border-slate-800 rounded-xl p-4 space-y-3">
              <span className="text-xs font-semibold text-slate-300 flex items-center gap-2">
                <Terminal className="w-4 h-4 text-cyan-400" />
                Jules Agent Reasoner Steps
              </span>

              <div className="space-y-2">
                {stepsList.map((step) => (
                  <div key={step.id} className="flex items-start space-x-3 text-xs">
                    <div className="mt-0.5">
                      {step.status === 'completed' ? (
                        <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                      ) : step.status === 'running' ? (
                        <RefreshCw className="w-4 h-4 text-cyan-400 animate-spin" />
                      ) : (
                        <div className="w-4 h-4 rounded-full border border-slate-700" />
                      )}
                    </div>
                    <div>
                      <span className={`font-semibold ${step.status === 'completed' ? 'text-slate-200' : step.status === 'running' ? 'text-cyan-300' : 'text-slate-500'}`}>
                        {step.title}
                      </span>
                      <p className="text-[11px] text-slate-400">{step.detail}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Result Patch */}
          {patchResult && (
            <div className="bg-slate-950 border border-slate-800 rounded-xl p-4 space-y-3">
              <div className="flex items-center justify-between">
                <div className="flex items-center space-x-2">
                  <ShieldCheck className="w-4 h-4 text-emerald-400" />
                  <span className="text-xs font-semibold text-slate-200">Jules Code Patch Proposal</span>
                </div>

                <div className="flex items-center space-x-2">
                  <button
                    onClick={handleCopyPatch}
                    className="px-2.5 py-1 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-lg text-xs flex items-center gap-1"
                  >
                    {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                    <span>{copied ? 'Copied' : 'Copy'}</span>
                  </button>

                  <button
                    onClick={() => {
                      onApplyPatch(patchResult);
                      onClose();
                    }}
                    className="px-3 py-1 bg-cyan-500 hover:bg-cyan-400 text-slate-950 font-bold text-xs rounded-lg transition-colors flex items-center gap-1"
                  >
                    <span>Apply Patch to Notebook</span>
                    <ArrowRight className="w-3.5 h-3.5" />
                  </button>
                </div>
              </div>

              {summaryNotes && (
                <div className="flex items-start justify-between bg-cyan-500/10 border border-cyan-500/20 p-2.5 rounded-lg">
                  <p className="text-xs text-cyan-300 font-mono">
                    {summaryNotes}
                  </p>
                  <button
                    onClick={handlePlaySpeech}
                    className={`ml-3 p-1.5 rounded-lg transition-colors flex-shrink-0 ${isSpeaking ? 'bg-cyan-500 text-slate-900 animate-pulse' : 'bg-slate-800 text-cyan-400 hover:bg-slate-700'}`}
                    title="Play Jules AI Voice"
                  >
                    <Volume2 className="w-4 h-4" />
                  </button>
                </div>
              )}

              <pre className="p-4 bg-slate-900 border border-slate-800 rounded-lg font-mono text-xs text-cyan-200 overflow-x-auto whitespace-pre leading-relaxed max-h-[220px]">
                {patchResult}
              </pre>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="px-6 py-3 border-t border-slate-800 bg-slate-950 flex items-center justify-between text-xs text-slate-500">
          <span className="flex items-center gap-1.5">
            Powered by Jules Autonomous Code Agent Framework
          </span>
          <button
            onClick={onClose}
            className="px-4 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-lg transition-colors"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
